export enum MedicineCategory {
  PRESCRIPTION = "PRESCRIPTION",
  OVER_THE_COUNTER = "OVER_THE_COUNTER",
  CONTROLLED_SUBSTANCE = "CONTROLLED_SUBSTANCE",
  VACCINE = "VACCINE",
  SURGICAL_SUPPLIES = "SURGICAL_SUPPLIES",
  OTHERS = "OTHERS"
}
